name: Reviewer Checklist

on:
  pull_request:
    types: [review_requested]

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract PR reviewer info
        id: pr_details
        run: |
          REVIEWERS=$(jq -r '.pull_request.requested_reviewers[].login' < $GITHUB_EVENT_PATH)
          NEW_REVIEWER=$(jq -r '.requested_reviewer.login' < $GITHUB_EVENT_PATH)
          ACTOR=$(jq -r '.sender.login' < $GITHUB_EVENT_PATH)
          echo "REVIEWERS=$REVIEWERS" >> $GITHUB_ENV
          echo "NEW_REVIEWER=$NEW_REVIEWER" >> $GITHUB_ENV
          echo "ACTOR=$ACTOR" >> $GITHUB_ENV

      - name: Determine checklist type
        id: checklist_type
        run: |
          # Only act if the user requested themselves
          if [ "$ACTOR" != "$NEW_REVIEWER" ]; then
            echo "SKIP=true" >> $GITHUB_ENV
            exit 0
          fi
          COUNT=$(echo "$REVIEWERS" | grep -c .)
          if [ "$COUNT" -eq "1" ]; then
            echo "TEMPLATE=main_rev_checklist.md" >> $GITHUB_ENV
            echo "SKIP=false" >> $GITHUB_ENV
          else
            echo "TEMPLATE=rev_checklist.md" >> $GITHUB_ENV
            echo "SKIP=false" >> $GITHUB_ENV
          fi

      - name: Prepare checklist
        if: env.SKIP == 'false'
        run: |
          sed "s/__REV__/${{ env.NEW_REVIEWER }}/g" .github/workflows/${{ env.TEMPLATE }} > filled_checklist.md

      - name: Post checklist as a comment
        if: env.SKIP == 'false'
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body-path: filled_checklist.md
